// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WpfListItem uIApplicationsListItem = this.UIWorkStationEnvironmeWindow.UIWindowsWorkStationDePane.UIBrowseViewObjectListList.UIApplicationsListItem;
            WpfListItem uIDOCUMENTSListItem = this.UIWorkStationEnvironmeWindow.UIWindowsWorkStationDePane.UIBrowseViewObjectListList.UIDOCUMENTSListItem;
            WpfListItem uIDossiersListItem = this.UIWorkStationEnvironmeWindow.UIWindowsWorkStationDePane.UIBrowseViewObjectListList.UIDossiersListItem;
            WpfListItem uIDashboardsListItem = this.UIWorkStationEnvironmeWindow.UIWindowsWorkStationDePane.UIBrowseViewObjectListList.UIDashboardsListItem;
            #endregion

            // Launch '%USERPROFILE%\Github\andrewzjl\WindowsWorkStationDemo\bin\Debug\WindowsWorkStationDemo.exe'
            ApplicationUnderTest uIWorkStationEnvironmeWindow = ApplicationUnderTest.Launch(this.RecordedMethod1Params.UIWorkStationEnvironmeWindowExePath, this.RecordedMethod1Params.UIWorkStationEnvironmeWindowAlternateExePath);

            // Click 'Applications' list item
            Mouse.Click(uIApplicationsListItem, new Point(56, 22));

            // Click 'DOCUMENTS' list item
            Mouse.Click(uIDOCUMENTSListItem, new Point(59, 21));

            // Click 'Dossiers' list item
            Mouse.Click(uIDossiersListItem, new Point(65, 5));

            // Click 'Dashboards' list item
            Mouse.Click(uIDashboardsListItem, new Point(72, 6));
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UIWorkStationEnvironmeWindow UIWorkStationEnvironmeWindow
        {
            get
            {
                if ((this.mUIWorkStationEnvironmeWindow == null))
                {
                    this.mUIWorkStationEnvironmeWindow = new UIWorkStationEnvironmeWindow();
                }
                return this.mUIWorkStationEnvironmeWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UIWorkStationEnvironmeWindow mUIWorkStationEnvironmeWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Launch '%USERPROFILE%\Github\andrewzjl\WindowsWorkStationDemo\bin\Debug\WindowsWorkStationDemo.exe'
        /// </summary>
        public string UIWorkStationEnvironmeWindowExePath = "C:\\Users\\Andrew\\Github\\andrewzjl\\WindowsWorkStationDemo\\bin\\Debug\\WindowsWorkStat" +
            "ionDemo.exe";
        
        /// <summary>
        /// Launch '%USERPROFILE%\Github\andrewzjl\WindowsWorkStationDemo\bin\Debug\WindowsWorkStationDemo.exe'
        /// </summary>
        public string UIWorkStationEnvironmeWindowAlternateExePath = "%USERPROFILE%\\Github\\andrewzjl\\WindowsWorkStationDemo\\bin\\Debug\\WindowsWorkStatio" +
            "nDemo.exe";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIWorkStationEnvironmeWindow : WpfWindow
    {
        
        public UIWorkStationEnvironmeWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "WorkStation - Environments";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("WorkStation - Environments");
            this.WindowTitles.Add("WorkStation - Applications");
            this.WindowTitles.Add("WorkStation - Dossiers");
            #endregion
        }
        
        #region Properties
        public UIWindowsWorkStationDePane UIWindowsWorkStationDePane
        {
            get
            {
                if ((this.mUIWindowsWorkStationDePane == null))
                {
                    this.mUIWindowsWorkStationDePane = new UIWindowsWorkStationDePane(this);
                }
                return this.mUIWindowsWorkStationDePane;
            }
        }
        #endregion
        
        #region Fields
        private UIWindowsWorkStationDePane mUIWindowsWorkStationDePane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIWindowsWorkStationDePane : WpfPane
    {
        
        public UIWindowsWorkStationDePane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfPane.PropertyNames.ClassName] = "Uia.Frame";
            this.SearchProperties[WpfPane.PropertyNames.AutomationId] = "sideBarFrame";
            this.WindowTitles.Add("WorkStation - Environments");
            this.WindowTitles.Add("WorkStation - Applications");
            this.WindowTitles.Add("WorkStation - Dossiers");
            #endregion
        }
        
        #region Properties
        public UIBrowseViewObjectListList UIBrowseViewObjectListList
        {
            get
            {
                if ((this.mUIBrowseViewObjectListList == null))
                {
                    this.mUIBrowseViewObjectListList = new UIBrowseViewObjectListList(this);
                }
                return this.mUIBrowseViewObjectListList;
            }
        }
        #endregion
        
        #region Fields
        private UIBrowseViewObjectListList mUIBrowseViewObjectListList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIBrowseViewObjectListList : WpfList
    {
        
        public UIBrowseViewObjectListList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfList.PropertyNames.AutomationId] = "BrowseViewObjectListBox";
            this.WindowTitles.Add("WorkStation - Environments");
            this.WindowTitles.Add("WorkStation - Applications");
            this.WindowTitles.Add("WorkStation - Dossiers");
            #endregion
        }
        
        #region Properties
        public WpfListItem UIApplicationsListItem
        {
            get
            {
                if ((this.mUIApplicationsListItem == null))
                {
                    this.mUIApplicationsListItem = new WpfListItem(this);
                    #region Search Criteria
                    this.mUIApplicationsListItem.SearchProperties[WpfListItem.PropertyNames.Name] = "Applications";
                    this.mUIApplicationsListItem.WindowTitles.Add("WorkStation - Environments");
                    #endregion
                }
                return this.mUIApplicationsListItem;
            }
        }
        
        public WpfListItem UIDOCUMENTSListItem
        {
            get
            {
                if ((this.mUIDOCUMENTSListItem == null))
                {
                    this.mUIDOCUMENTSListItem = new WpfListItem(this);
                    #region Search Criteria
                    this.mUIDOCUMENTSListItem.SearchProperties[WpfListItem.PropertyNames.Name] = "DOCUMENTS";
                    this.mUIDOCUMENTSListItem.WindowTitles.Add("WorkStation - Applications");
                    #endregion
                }
                return this.mUIDOCUMENTSListItem;
            }
        }
        
        public WpfListItem UIDossiersListItem
        {
            get
            {
                if ((this.mUIDossiersListItem == null))
                {
                    this.mUIDossiersListItem = new WpfListItem(this);
                    #region Search Criteria
                    this.mUIDossiersListItem.SearchProperties[WpfListItem.PropertyNames.Name] = "Dossiers";
                    this.mUIDossiersListItem.WindowTitles.Add("WorkStation - Applications");
                    #endregion
                }
                return this.mUIDossiersListItem;
            }
        }
        
        public WpfListItem UIDashboardsListItem
        {
            get
            {
                if ((this.mUIDashboardsListItem == null))
                {
                    this.mUIDashboardsListItem = new WpfListItem(this);
                    #region Search Criteria
                    this.mUIDashboardsListItem.SearchProperties[WpfListItem.PropertyNames.Name] = "Dashboards";
                    this.mUIDashboardsListItem.WindowTitles.Add("WorkStation - Dossiers");
                    #endregion
                }
                return this.mUIDashboardsListItem;
            }
        }
        #endregion
        
        #region Fields
        private WpfListItem mUIApplicationsListItem;
        
        private WpfListItem mUIDOCUMENTSListItem;
        
        private WpfListItem mUIDossiersListItem;
        
        private WpfListItem mUIDashboardsListItem;
        #endregion
    }
}
